development:
  adapter: postgresql
  encoding: unicode
  database: leonards_development
  pool: 5
  username: leonards
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: theleona_db
  pool: 5
  username: theleona_p
  password: "911234"
  socket: /tmp/mysql.sock
